# Generated by Django 5.2.1 on 2025-05-15 21:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Formateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Stagiaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Formation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("date_debut", models.DateField(default=datetime.date.today)),
                ("date_fin", models.DateField(default=datetime.date.today)),
                ("duree_jours", models.IntegerField()),
                (
                    "formateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="formations.formateur",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Inscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_inscription", models.DateField(auto_now_add=True)),
                (
                    "formation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="formations.formation",
                    ),
                ),
                (
                    "stagiaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="formations.stagiaire",
                    ),
                ),
            ],
        ),
    ]
