# Generated by Django 5.2.1 on 2025-05-16 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoteFormation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.IntegerField()),
                (
                    "formation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="formations.formation",
                    ),
                ),
                (
                    "stagiaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="formations.stagiaire",
                    ),
                ),
            ],
            options={
                "unique_together": {("stagiaire", "formation")},
            },
        ),
    ]
