# Generated by Django 5.2.1 on 2025-05-16 12:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formations", "0002_noteformation"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="noteformation",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="noteformation",
            name="commentaire",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="noteformation",
            name="note",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
    ]
